INSERT INTO PUBLIC.DRIVER (ID, NAME, VEHICLE) VALUES (10001, 'Flavinho do Pneu', 'flavinhodopneu@gmail.com');
INSERT INTO PUBLIC.DRIVER (ID, NAME, VEHICLE) VALUES (10002, 'Maria da Silva', 'mariadasilva@gmail.com');
INSERT INTO PUBLIC.DRIVER (ID, NAME, VEHICLE) VALUES (10003, 'João Souza', 'joaosouza@gmail.com');
INSERT INTO PUBLIC.DRIVER (ID, NAME, VEHICLE) VALUES (10004, 'Ana Oliveira', 'anaoliveira@gmail.com');
INSERT INTO PUBLIC.DRIVER (ID, NAME, VEHICLE) VALUES (10005, 'Carlos Santos', 'carlossantos@gmail.com');
INSERT INTO PUBLIC.DRIVER (ID, NAME, VEHICLE) VALUES (10006, 'Fernanda Costa', 'fernandacosta@gmail.com');
INSERT INTO PUBLIC.DRIVER (ID, NAME, VEHICLE) VALUES (10007, 'Rafaela Pereira', 'rafaelapereira@gmail.com');
INSERT INTO PUBLIC.DRIVER (ID, NAME, VEHICLE) VALUES (10008, 'Pedro Rodrigues', 'pedrorodrigues@gmail.com');
INSERT INTO PUBLIC.DRIVER (ID, NAME, VEHICLE) VALUES (10009, 'Lucas Ferreira', 'lucasferreira@gmail.com');
INSERT INTO PUBLIC.DRIVER (ID, NAME, VEHICLE) VALUES (10010, 'Mariana Almeida', 'marianaalmeida@gmail.com');
INSERT INTO PUBLIC.DRIVER (ID, NAME, VEHICLE) VALUES (10011, 'Juliana Martins', 'julianamartins@gmail.com');
INSERT INTO PUBLIC.DRIVER (ID, NAME, VEHICLE) VALUES (10012, 'Gustavo Lima', 'gustavolima@gmail.com');
INSERT INTO PUBLIC.DRIVER (ID, NAME, VEHICLE) VALUES (10013, 'Paula Pereira', 'paulapereira@gmail.com');
INSERT INTO PUBLIC.DRIVER (ID, NAME, VEHICLE) VALUES (10014, 'Roberto Santos', 'robertosantos@gmail.com');
INSERT INTO PUBLIC.DRIVER (ID, NAME, VEHICLE) VALUES (10015, 'Cristina Oliveira', 'cristinaoliveira@gmail.com');
INSERT INTO PUBLIC.DRIVER (ID, NAME, VEHICLE) VALUES (10016, 'Marcos Silva', 'marcossilva@gmail.com');
INSERT INTO PUBLIC.DRIVER (ID, NAME, VEHICLE) VALUES (10017, 'Larissa Sousa', 'larissasousa@gmail.com');
INSERT INTO PUBLIC.DRIVER (ID, NAME, VEHICLE) VALUES (10018, 'Rodrigo Almeida', 'rodrigoalmeida@gmail.com');
INSERT INTO PUBLIC.DRIVER (ID, NAME, VEHICLE) VALUES (10019, 'Aline Mendes', 'alinemendes@gmail.com');
INSERT INTO PUBLIC.DRIVER (ID, NAME, VEHICLE) VALUES (10020, 'Felipe Nunes', 'felipenunes@gmail.com');
INSERT INTO PUBLIC.DRIVER (ID, NAME, VEHICLE) VALUES (10021, 'Tatiane Pereira', 'tatianepereira@gmail.com');
